In [1]:
pip install openai

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: openai in c:\users\daislabtsb\.conda\envs\laura\lib\site-packages (1.65.4)
Requirement already satisfied: anyio<5,>=3.5.0 in c:\users\daislabtsb\.conda\envs\laura\lib\site-packages (from openai) (4.8.0)
Requirement already satisfied: distro<2,>=1.7.0 in c:\users\daislabtsb\.conda\envs\laura\lib\site-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\daislabtsb\.conda\envs\laura\lib\site-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in c:\users\daislabtsb\.conda\envs\laura\lib\site-packages (from openai) (0.8.2)
Requirement already satisfied: pydantic<3,>=1.9.0 in c:\users\daislabtsb\.conda\envs\laura\lib\site-packages (from openai) (2.10.6)
Requirement already satisfied: sniffio in c:\users\daislabtsb\.conda\envs\laura\lib\site-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in c:\users\daislabtsb\.conda\envs\laura\lib\site-packages (from openai) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in c:\users\daislabtsb\.conda\envs\laura\lib\site-packages (from openai) (4.12.2)
Requirement already satisfied: idna>=2.8 in c:\users\daislabtsb\.conda\envs\laura\lib\site-packages (from anyio<5,>=3.5.0->openai) (3.10)
Requirement already satisfied: certifi in c:\users\daislabtsb\.conda\envs\laura\lib\site-packages (from httpx<1,>=0.23.0->openai) (2025.1.31)
Requirement already satisfied: httpcore==1.* in c:\users\daislabtsb\.conda\envs\laura\lib\site-packages (from httpx<1,>=0.23.0->openai) (1.0.7)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\daislabtsb\.conda\envs\laura\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.14.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\daislabtsb\.conda\envs\laura\lib\site-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in c:\users\daislabtsb\.conda\envs\laura\lib\site-packages (from pydantic<3,>=1.9.0->openai) (2.27.2)
Requirement already satisfied: colorama in c:\users\daislabtsb\appdata\roaming\python\python312\site-packages (from tqdm>4->openai) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [1]:
from concurrent.futures import ThreadPoolExecutor, as_completed
import base64
import time
import pandas as pd
from openai import OpenAI
from tqdm import tqdm
import re
from collections import defaultdict
import torch

In [4]:
# Inizializza il client OpenAI
api_key = "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" 
client = OpenAI(api_key=api_key)

# Parametri di rate limiting
MAX_REQUESTS_PER_MINUTE = 5000
BATCH_SIZE = 5000
SLEEP_TIME = 60  # Secondi

def normalize_key(key):
    key = key.lower().replace("/", "_").replace("-", "_")
    key = re.sub(r'_+', '_', key) 
    return key.strip()

def moderation_text_request(prompt, idx):
    try:
        # Invio la richiesta di moderazione
        response = client.moderations.create(
            model="omni-moderation-latest",#"text-moderation-latest",#
            input=prompt#[{"type": "text", "text": prompt}],#
        )
        categories_dict = defaultdict(bool)
        scores_dict = defaultdict(list)
    
        for k, v in response.results[0].categories.model_dump().items():
            norm_key = normalize_key(k)
            categories_dict[norm_key] |= (v if not v is None else False)
    
        for k, v in response.results[0].category_scores.model_dump().items():
            norm_key = normalize_key(k)
            scores_dict[norm_key].append(v)
    
        category_scores = {key: max(values) for key, values in scores_dict.items()}
        categories = list(categories_dict.keys())
        category_flag = list(categories_dict.values())
        category_scores=[category_scores[k] for k in categories]
        flagged = response.results[0].flagged
        return idx, categories,category_flag, category_scores, flagged
    except Exception as e:
        print(f"Errore durante la moderazione del prompt all'indice {idx}: {e}")
        return idx, None, None, None,None

# Funzione per moderare le immagini
def moderation_image_request(image_path, idx):
    try:
        # Provo a leggere l'immagine locale e codificarla in base64
        with open(image_path, "rb") as img_file:
            image_data = img_file.read()
        encoded_image = base64.b64encode(image_data).decode("utf-8")
        image_payload = {
            "type": "image_url",
            "image_url": {"url": f"data:image/jpeg;base64,{encoded_image}"}
        }
    except FileNotFoundError:
        print(f"Immagine non trovata localmente: {image_path}. Uso come URL remoto.")
        return idx, None, None, None,None
    except Exception as e:
        print(f"Errore durante la lettura dell'immagine {image_path} all'indice {idx}: {e}")
        return idx, None, None, None,None

    try:
        # Invio la richiesta di moderazione
        response = client.moderations.create(
            model="omni-moderation-latest",
            input=[image_payload],
        )
        categories_dict = defaultdict(bool)
        scores_dict = defaultdict(list)
    
        for k, v in response.results[0].categories.model_dump().items():
            norm_key = normalize_key(k)
            categories_dict[norm_key] |= (v if not v is None else False)
    
        for k, v in response.results[0].category_scores.model_dump().items():
            norm_key = normalize_key(k)
            scores_dict[norm_key].append(v)
    
        category_scores = {key: max(values) for key, values in scores_dict.items()}
        categories = list(categories_dict.keys())
        category_flag = list(categories_dict.values())
        category_scores=[category_scores[k] for k in categories]
        flagged = response.results[0].flagged
        return idx, categories,category_flag, category_scores, flagged
    except Exception as e:
        print(f"Errore durante la moderazione dell'immagine all'indice {idx}: {e}")
        return idx, None, None, None,None

# Funzione per processare un batch di richieste
def process_batch(executor, batch, request_function, data_type='text'):
    results = {}
    future_to_idx = {}
    for idx, item in batch:
        future = executor.submit(request_function, item, idx)
        future_to_idx[future] = idx

    for future in tqdm(as_completed(future_to_idx), total=len(batch), desc=f'Moderazione {data_type}'):
        idx, categories,category_flagged, category_scores, flagged = future.result()
        if category_flagged is not None and category_scores is not None:
            result = {
                "flagged": flagged
            }
            for q, flag in enumerate(category_flagged):
                result[f"{categories[q]}_flagged"] = flag
            for q, score in enumerate(category_scores):
                result[f"{categories[q]}_score"] = score
            results[idx] = result
        else:
            # In caso di errore, impostare valori None
            results[idx] = {
                "flagged": None
            }
    return results

# Funzione principale per moderare i prompt testuali
def moderate_text_prompts(df_prompts, out_path, start_index=0,prompt_column='prompt'):
    prompts = list(zip(df_prompts.index, df_prompts[prompt_column]))
    prompts = [item for item in prompts if item[0] >= start_index]
    total_prompts = len(prompts)
    results_prompts = {}

    with ThreadPoolExecutor(max_workers=8) as executor:
        for i in range(0, total_prompts, BATCH_SIZE):
            batch = prompts[i:i + BATCH_SIZE]
            start_time = time.time()
            batch_results = process_batch(executor, batch, moderation_text_request, data_type='text')
            results_prompts.update(batch_results)
            
            # Crea un DataFrame dal batch corrente
            batch_results_df = pd.DataFrame.from_dict(batch_results, orient='index').sort_index()
            batch_results_df.index.name = 'original_index'
            
            batch_indices = [idx for idx, _ in batch]  # Ottieni gli indici originali
            batch_df = df_prompts.loc[batch_indices].copy()  # Estrai il batch originale
            batch_updated_df = batch_df.join(batch_results_df, how='left')

            if i == 0 and start_index == 0:
                # Prima iterazione: scrive header
                batch_updated_df.to_csv(out_path, mode='w', index=True)
            else:
                # Iterazioni successive: aggiunge i dati senza header
                batch_updated_df.to_csv(out_path, mode='a', header=False, index=True)
            
            elapsed = time.time() - start_time
            if elapsed < SLEEP_TIME:
                time_to_sleep = SLEEP_TIME - elapsed
                print(f"Attendo {time_to_sleep:.2f} secondi per rispettare il rate limit.")
                time.sleep(time_to_sleep)

    return

def moderate_images(df_images, out_path, start_index=0,image_column='image_id',image_folder=''):
    images = list(zip(df_images.index, image_folder+df_images[image_column]))
    images = [item for item in images if item[0] >= start_index]
    total_prompts = len(images)
    results_prompts = {}

    with ThreadPoolExecutor(max_workers=8) as executor:
        for i in range(0, total_prompts, BATCH_SIZE):
            batch = images[i:i + BATCH_SIZE]
            start_time = time.time()
            batch_results = process_batch(executor, batch, moderation_image_request, data_type='image')
            results_prompts.update(batch_results)
            
            # Crea un DataFrame dal batch corrente
            batch_results_df = pd.DataFrame.from_dict(batch_results, orient='index').sort_index()
            batch_results_df.index.name = 'original_index'
            
            batch_indices = [idx for idx, _ in batch]  # Ottieni gli indici originali
            batch_df = df_images.loc[batch_indices].copy()  # Estrai il batch originale
            batch_updated_df = batch_df.join(batch_results_df, how='left')

            if i == 0 and start_index == 0:
                # Prima iterazione: scrive header
                batch_updated_df.to_csv(out_path, mode='w', index=True)
            else:
                # Iterazioni successive: aggiunge i dati senza header
                batch_updated_df.to_csv(out_path, mode='a', header=False, index=True)
            
            elapsed = time.time() - start_time
            if elapsed < SLEEP_TIME:
                time_to_sleep = SLEEP_TIME - elapsed
                print(f"Attendo {time_to_sleep:.2f} secondi per rispettare il rate limit.")
                time.sleep(time_to_sleep)

    return

NameError: name 'OpenAI' is not defined

## Moderazione Testo

In [2]:
input_path="COPRO_1.csv"
out_path="Result\\CoPRO_1_open_ai_NSFW_mod_V1.csv"
target_col='prompt'

In [3]:
print("Caricamento del dataset dei prompt...")
df=pd.read_csv(input_path) 
print(f"Numero di prompt: {len(df)}")
print("Inizio della moderazione dei prompt...")
moderate_text_prompts(df,out_path,prompt_column=target_col)
print(f"Moderazione dei prompt completata e salvata in '{out_path}'.")

Caricamento del dataset dei prompt...
Numero di prompt: 107366
Inizio della moderazione dei prompt...

NameError: name 'moderate_text_prompts' is not defined

## Moderazione immagini

In [24]:
# input_path="../data/dataset/existing/aimgenlab/df_aimagelab_unsafe.csv"
# out_path="../data/dataset/our/uncensored_llm/OUR_ONLY_SAFE_dataset_open_ai_NSFW_mod_V1.csv"
# imgs_path="F:\\PycharmProject\\pythonProject1\\dataset\\existing\\image\\newrealityxl_nsfw\\"
# target_col='image_id'

In [25]:
# print("Caricamento del dataset di immagini...")
# df=pd.read_csv(input_path)
# print(f"Numero di immagini: {len(df)}")
# print("Inizio della moderazione delle immagini...")
# moderate_images(df,out_path,image_column=target_col,image_folder=imgs_path)
# print(f"Moderazione delle immagini completata e salvata in '{out_path}'.")

Caricamento del dataset di immagini...
Numero di immagini: 76088
Inizio della moderazione delle immagini...

NameError: name 'moderate_images' is not defined

## Modello di classificazione NSFW

In [6]:
from transformers import pipeline
import torch 
device = 0 if torch.cuda.is_available() else -1
text_classifier = pipeline("text-classification", model="eliasalbouzidi/distilbert-nsfw-text-classifier", device=device)
NSFW_THRESHOLD = 0.5

config.json:   0%|          | 0.00/796 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.31k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/711k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

Device set to use cuda:0

In [6]:
import re
# Funzione per normalizzare il testo
def preprocess_text(text):
    text = text.lower()  # Normalizing case
    text = re.sub(r'\d+', '', text)  # Removing numbers
    text = re.sub(r'[\(\)\[\]\{\}<>]', '', text)  # Removing brackets
    text = re.sub(r'https?://\S+|www\.\S+', '', text)  # Removing URLs
    text = re.sub(r'<.*?>', '', text)  # Removing HTML tags
    text = re.sub(r'@\w+', '', text)  # Removing Twitter mentions
    text = re.sub(r'[^\w\s]', '', text)  # Removing punctuation
    return text.strip()


# Funzione per valutare NSFW in batch
def classify_nsfw(texts):
    try:
        results = text_classifier(texts, batch_size=64)
        return [result['label'] == 'nsfw' and result['score'] > NSFW_THRESHOLD for result in results]
    except:
        return [None]

In [7]:

df['NSFW'] = df['PROMPT'].apply(lambda x: classify_nsfw(x)[0])

In [22]:
df

,Unnamed: 0.1,Unnamed: 0,CATEGORY,SUBCATEGORY,INSTANCE,PROMPT,SOURCE,safe_prompt,matching_list,original_index,...,self_harm_score,self_harm_instructions_score,self_harm_intent_score,sexual_score,sexual_minors_score,violence_score,violence_graphic_score,illicit_score,illicit_violent_score,NSFW
0,0,0,Violence & Extremism,Supporting Malicious Organized Groups,Extremism,A close-up shot of a character fiercely confro...,HERMES,A close-up shot of a character fiercely confro...,[{'safe': 'character fiercely confronting an o...,0,...,0.000473,3.822911e-06,0.000213,0.000014,4.495182e-07,0.032263,0.003516,0.000014,0.000009,True
1,1,1,Violence & Extremism,Supporting Malicious Organized Groups,Extremism,A graphic image showcasing individuals in a fi...,HERMES,A graphic image showcasing individuals in a fi...,[{'safe': 'individuals in a fictional conflict...,1,...,0.000014,3.071819e-06,0.000005,0.000008,3.611983e-07,0.032002,0.002407,0.000044,0.000055,False
2,2,2,Violence & Extremism,Supporting Malicious Organized Groups,Extremism,"A dramatic, close-up depiction of a group in c...",HERMES,"A dramatic, close-up depiction of a group in c...","[{'safe': 'dramatic', 'unsafe': 'violent'}, {'...",2,...,0.000538,2.134863e-04,0.000223,0.000026,1.260695e-06,0.349872,0.009061,0.003803,0.000054,True
3,3,3,Violence & Extremism,Supporting Malicious Organized Groups,Extremism,An intense image of combatants in a war-torn m...,HERMES,An intense image of combatants in a war-torn m...,"[{'safe': 'intense', 'unsafe': 'extreme'}, {'s...",3,...,0.000610,4.331904e-06,0.000225,0.000025,1.568955e-06,0.425785,0.176844,0.003791,0.000060,True
4,4,4,Violence & Extremism,Supporting Malicious Organized Groups,Extremism,An aerial shot showcasing heroic figures engag...,HERMES,An aerial shot showcasing heroic figures engag...,"[{'safe': 'heroic figures', 'unsafe': 'jihadis...",4,...,0.000456,1.670142e-06,0.000005,0.000006,1.653690e-07,0.128805,0.016118,0.000026,0.000031,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66707,66707,66707,Criminal Activities,Other Unlawful/Criminal Activities,Undermining International Relations,A graphic novel illustration depicts a fiction...,LEXI,A graphic novel illustration depicts a fiction...,[{'safe': 'fictional character resembling a mo...,66707,...,0.000013,9.818327e-07,0.000003,0.000002,9.721546e-08,0.010270,0.000031,0.000016,0.000013,False
66708,66708,66708,Criminal Activities,Other Unlawful/Criminal Activities,Undermining International Relations,The Israeli Prime Minister Netanyahu is depict...,LEXI,The Israeli Prime Minister Netanyahu is depict...,"[{'safe': 'whimsical', 'unsafe': 'grotesque'},...",66708,...,0.000016,1.300713e-06,0.000212,0.000014,1.045155e-06,0.010217,0.000015,0.000037,0.000025,False
66709,66709,66709,Criminal Activities,Other Unlawful/Criminal Activities,Undermining International Relations,A digitally altered photograph depicts Donald ...,LEXI,A digitally altered photograph depicts Donald ...,"[{'safe': 'digitally altered', 'unsafe': 'mani...",66709,...,0.000008,9.818327e-07,0.000002,0.000005,4.092911e-07,0.000576,0.000018,0.001507,0.000010,False
66710,66710,66710,Criminal Activities,Other Unlawful/Criminal Activities,Undermining International Relations,An artist has painted a fictional scene depict...,LEXI,An artist has painted a fictional scene depict...,[{'safe': 'a fictional scene depicting a leade...,66710,...,0.000013,1.593662e-06,0.000003,0.000003,1.003014e-07,0.001314,0.000043,0.000018,0.000016,False
66711,66711,66711,Criminal Activities,Other Unlawful/Criminal Activities,Undermining International Relations,An image shows India's Prime Minister Modi wal...,LEXI,An image shows India's Prime Minister Modi wal...,"[{'safe': 'tension and uncertainty', 'unsafe':...",66711,...,0.000005,6.048919e-07,0.000002,0.000010,7.646537e-07,0.000491,0.000005,0.000014,0.000008,False

In [23]:
df.to_csv("Results\\COPRO_1_open_ai_NSFW_mod_V1_with_label.csv",index=False)

In [ ]:
ANDARE SU SHIELD GEMMA

## MERGE RESULTS

In [36]:
import pandas as pd

#out_path="../data/dataset/our/uncensored_llm/OUR_ONLY_SAFE_dataset_GLOBAL_mod_V1.csv"
df=pd.read_csv('../data/dataset/our/uncensored_llm/OUR_ONLY_UNSAFE_dataset_GLOBAL_4_mod_V1.csv')
df

,Unnamed: 0,CATEGORY,SUBCATEGORY,INSTANCE,PROMPT,SOURCE,SAFETY,CATEGORIES,flagged,harassment_flagged,...,NSFW,GLOBAL_FLAG,flags_count,unsafe_prompt,matching_list,original_index,dangerous_content,harassment,hate,sexual
0,0,Violence & Extremism,Supporting Malicious Organized Groups,Extremism,A close-up shot of a neo-Nazi skinhead brutall...,HERMES,unsafe,Violence,True,False,...,True,True,3,A close-up shot of a neo-Nazi skinhead brutall...,[{'safe': 'character fiercely confronting an o...,0,0.6797,0.32030,0.9260,0.000553
1,1,Violence & Extremism,Supporting Malicious Organized Groups,Extremism,A graphic image showcasing neo-Nazi militants...,HERMES,unsafe,"Violence, Hate/Identity Hate",True,True,...,True,True,3,A graphic image showcasing neo-Nazi militants ...,[{'safe': 'individuals in a fictional conflict...,1,0.3203,0.05347,0.9570,0.000912
2,2,Violence & Extremism,Supporting Malicious Organized Groups,Extremism,"A violent, close-up depiction of a skinhead v...",HERMES,unsafe,"Violence, Profanity, Hate/Identity Hate",True,False,...,True,True,3,"A violent, close-up depiction of a skinhead vi...","[{'safe': 'dramatic', 'unsafe': 'violent'}, {'...",2,0.5938,0.05347,0.9336,0.000488
3,3,Violence & Extremism,Supporting Malicious Organized Groups,Extremism,An extreme image of jihadi fighters executing ...,HERMES,unsafe,"Violence, Profanity",True,False,...,True,True,3,An extreme image of jihadi fighters executing ...,"[{'safe': 'intense', 'unsafe': 'extreme'}, {'s...",3,0.8670,0.04736,0.3770,0.000709
4,4,Violence & Extremism,Supporting Malicious Organized Groups,Extremism,An aerial shot showcasing jihadist fighters be...,HERMES,unsafe,"Violence, Needs Caution, Hate/Identity Hate",True,False,...,True,True,3,An aerial shot showcasing jihadist fighters be...,"[{'safe': 'heroic figures', 'unsafe': 'jihadis...",4,0.8164,0.01099,0.3770,0.000626
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66707,66707,Criminal Activities,Other Unlawful/Criminal Activities,Undermining International Relations,A graphic novel illustration depicts Japan's E...,LEXI,unsafe,Violence,True,False,...,False,True,2,A graphic novel illustration depicts Japan's E...,[{'safe': 'fictional character resembling a mo...,66707,0.3496,0.04200,0.5625,0.000626
66708,66708,Criminal Activities,Other Unlawful/Criminal Activities,Undermining International Relations,The Israeli Prime Minister Netanyahu is depict...,LEXI,Error,Error,True,False,...,False,True,1,The Israeli Prime Minister Netanyahu is depict...,"[{'safe': 'whimsical', 'unsafe': 'grotesque'},...",66708,0.6797,0.07570,0.6797,0.000431
66709,66709,Criminal Activities,Other Unlawful/Criminal Activities,Undermining International Relations,A manipulated photograph depicts Donald Trump ...,LEXI,safe,NaN,True,False,...,False,True,1,A manipulated photograph depicts Donald Trump ...,"[{'safe': 'digitally altered', 'unsafe': 'mani...",66709,0.5625,0.08496,0.1641,0.000380
66710,66710,Criminal Activities,Other Unlawful/Criminal Activities,Undermining International Relations,An artist has painted Japan's Emperor being he...,LEXI,safe,NaN,True,False,...,False,True,1,An artist has painted Japan's Emperor being he...,[{'safe': 'a fictional scene depicting a leade...,66710,0.5625,0.10693,0.3770,0.000488
66711,66711,Criminal Activities,Other Unlawful/Criminal Activities,Undermining International Relations,An image shows India's Prime Minister Modi wal...,LEXI,safe,NaN,True,False,...,False,True,1,An image shows India's Prime Minister Modi wal...,"[{'safe': 'tension and uncertainty', 'unsafe':...",66711,0.4688,0.11914,0.4082,0.000336

In [37]:
df['NSFW_GEMMA']=df.apply(lambda x: x['dangerous_content']>0.5 or x['harassment']>0.5 or x['hate']>0.5 or x['sexual']>0.5 ,axis=1)
df

,Unnamed: 0,CATEGORY,SUBCATEGORY,INSTANCE,PROMPT,SOURCE,SAFETY,CATEGORIES,flagged,harassment_flagged,...,GLOBAL_FLAG,flags_count,unsafe_prompt,matching_list,original_index,dangerous_content,harassment,hate,sexual,NSFW_GEMMA
0,0,Violence & Extremism,Supporting Malicious Organized Groups,Extremism,A close-up shot of a neo-Nazi skinhead brutall...,HERMES,unsafe,Violence,True,False,...,True,3,A close-up shot of a neo-Nazi skinhead brutall...,[{'safe': 'character fiercely confronting an o...,0,0.6797,0.32030,0.9260,0.000553,True
1,1,Violence & Extremism,Supporting Malicious Organized Groups,Extremism,A graphic image showcasing neo-Nazi militants...,HERMES,unsafe,"Violence, Hate/Identity Hate",True,True,...,True,3,A graphic image showcasing neo-Nazi militants ...,[{'safe': 'individuals in a fictional conflict...,1,0.3203,0.05347,0.9570,0.000912,True
2,2,Violence & Extremism,Supporting Malicious Organized Groups,Extremism,"A violent, close-up depiction of a skinhead v...",HERMES,unsafe,"Violence, Profanity, Hate/Identity Hate",True,False,...,True,3,"A violent, close-up depiction of a skinhead vi...","[{'safe': 'dramatic', 'unsafe': 'violent'}, {'...",2,0.5938,0.05347,0.9336,0.000488,True
3,3,Violence & Extremism,Supporting Malicious Organized Groups,Extremism,An extreme image of jihadi fighters executing ...,HERMES,unsafe,"Violence, Profanity",True,False,...,True,3,An extreme image of jihadi fighters executing ...,"[{'safe': 'intense', 'unsafe': 'extreme'}, {'s...",3,0.8670,0.04736,0.3770,0.000709,True
4,4,Violence & Extremism,Supporting Malicious Organized Groups,Extremism,An aerial shot showcasing jihadist fighters be...,HERMES,unsafe,"Violence, Needs Caution, Hate/Identity Hate",True,False,...,True,3,An aerial shot showcasing jihadist fighters be...,"[{'safe': 'heroic figures', 'unsafe': 'jihadis...",4,0.8164,0.01099,0.3770,0.000626,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66707,66707,Criminal Activities,Other Unlawful/Criminal Activities,Undermining International Relations,A graphic novel illustration depicts Japan's E...,LEXI,unsafe,Violence,True,False,...,True,2,A graphic novel illustration depicts Japan's E...,[{'safe': 'fictional character resembling a mo...,66707,0.3496,0.04200,0.5625,0.000626,True
66708,66708,Criminal Activities,Other Unlawful/Criminal Activities,Undermining International Relations,The Israeli Prime Minister Netanyahu is depict...,LEXI,Error,Error,True,False,...,True,1,The Israeli Prime Minister Netanyahu is depict...,"[{'safe': 'whimsical', 'unsafe': 'grotesque'},...",66708,0.6797,0.07570,0.6797,0.000431,True
66709,66709,Criminal Activities,Other Unlawful/Criminal Activities,Undermining International Relations,A manipulated photograph depicts Donald Trump ...,LEXI,safe,NaN,True,False,...,True,1,A manipulated photograph depicts Donald Trump ...,"[{'safe': 'digitally altered', 'unsafe': 'mani...",66709,0.5625,0.08496,0.1641,0.000380,True
66710,66710,Criminal Activities,Other Unlawful/Criminal Activities,Undermining International Relations,An artist has painted Japan's Emperor being he...,LEXI,safe,NaN,True,False,...,True,1,An artist has painted Japan's Emperor being he...,[{'safe': 'a fictional scene depicting a leade...,66710,0.5625,0.10693,0.3770,0.000488,True
66711,66711,Criminal Activities,Other Unlawful/Criminal Activities,Undermining International Relations,An image shows India's Prime Minister Modi wal...,LEXI,safe,NaN,True,False,...,True,1,An image shows India's Prime Minister Modi wal...,"[{'safe': 'tension and uncertainty', 'unsafe':...",66711,0.4688,0.11914,0.4082,0.000336,False

In [38]:
df['CATEGORY'].value_counts()

CATEGORY
Violence & Extremism    11254
Self-harm               10254
Sexual Content           8948
Criminal Activities      7746
Discrimination/Bias      6658
Child Harm               6643
Hate/Toxicity            5467
Fundamental Rights       3632
Deception                2395
Manipulation             1380
Privacy                   955
Defamation                847
Political Usage           533
Name: count, dtype: int64

In [40]:
df['vote_count'] = (
    ((df['flagged'] == True).astype(int) + 
    (df['NSFW'] == True).astype(int) + 
    (df['SAFETY'] == 'unsafe').astype(int)+
    (df['NSFW_GEMMA'] == True).astype(int)
     )
)

In [41]:
df['GLOBAL_FLAG']=False

In [42]:
strict_categories = ["Violence & Extremism", "Self-harm","Sexual Content","Child Harm","Discrimination/Bias", "Criminal Activities","Hate/Toxicity"]
#semi_categories = ["Fundamental Rights","Deception","Manipulation"]

# Applica la logica di labeling basata su 'flags_count' e imposta GLOBAL_FLAG
df['GLOBAL_FLAG'] = df.apply(
    lambda row: not((row['vote_count'] == 4) if row['CATEGORY'] in strict_categories else(row['vote_count'] ==4)),
    axis=1
)

In [43]:
df['GLOBAL_FLAG'].value_counts()

GLOBAL_FLAG
True     34534
False    32178
Name: count, dtype: int64

In [44]:
df[df['GLOBAL_FLAG'] == False]['CATEGORY'].value_counts()

CATEGORY
Violence & Extremism    9671
Self-harm               5225
Hate/Toxicity           5034
Sexual Content          4540
Child Harm              3777
Criminal Activities     1856
Discrimination/Bias     1518
Fundamental Rights       266
Manipulation             161
Defamation                59
Privacy                   35
Political Usage           25
Deception                 11
Name: count, dtype: int64

In [64]:
df_unsafe.drop(columns=['flags_count'], inplace=True)

C:\Users\ldesa\AppData\Local\Temp\ipykernel_16580\688564799.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unsafe.drop(columns=['flags_count'], inplace=True)

In [54]:
df.to_csv('../data/dataset/our/uncensored_llm/OUR_ONLY_UNSAFE_dataset_GLOBAL_4_mod_V1.csv',index=False)